n_epochs: 25
n_iter_train: 50
n_iter_test: 50
learning_rate: 1.0e-2
sigma: 3.3e-0
omega: 1.7
unroll: False
fpi: False
n_iter_bwd: 25
equilibrate:
  max_iter: 0
  tol: 1.0e-3
  ord: 2.0
  col_scaling: False
  update_mode: "Gauss"
  safeguard: False
