n_epochs: 25
n_iter_train: 350
n_iter_test: 350
learning_rate: 1.0e-2
sigma: 3.282890975060525
omega: 1.7
unroll: False
fpi: False
n_iter_bwd: 25
equilibrate:
  max_iter: 0
  tol: 1.0e-3
  ord: 2.0
  col_scaling: False
  update_mode: "Gauss"
  safeguard: False
features_list: [200, 200]
activation: relu
