n_epochs: 250
n_iter_train: 100
n_iter_test: 1000
learning_rate: 1.0e-3
sigma: 0.01
omega: 1.7
unroll: False
fpi: True
n_iter_bwd: 100
raw: False
activation: relu
equilibrate:
  max_iter: 0
  tol: 1.0e-3
  ord: 2.0
  col_scaling: False
  update_mode: "Gauss"
  safeguard: False
features_list: [200, 200]
val_split: 0.1
test_split: 0.1
batch_size: 2048
